<section>
    <main>
        <section class="planes-container">
            <h2>Elige el plan que mejor se adapte a tus necesidades.</h2>            
            <div class="plan">
                <h3>Plan Básico</h3>
                <p class="price">$19/mes</p>
                <ul>
                    <li>Monitoreo básico</li>
                    <li>Soporte limitado</li>
                    <li>Acceso a estadísticas</li>
                </ul>
                <button class="cta-button">Seleccionar Plan</button>
            </div>

            <div class="plan featured">
                <h3>Plan Profesional</h3>
                <p class="price">$49/mes</p>
                <ul>
                    <li>Monitoreo avanzado</li>
                    <li>Soporte prioritario</li>
                    <li>Acceso a análisis detallado</li>
                    <li>Alertas personalizadas</li>
                </ul>
                <button class="cta-button">Seleccionar Plan</button>
            </div>

            <div class="plan">
                <h3>Plan Premium</h3>
                <p class="price">$99/mes</p>
                <ul>
                    <li>Monitoreo completo</li>
                    <li>Soporte 24/7</li>
                    <li>Acceso a datos en tiempo real</li>
                    <li>Asesoría personalizada</li>
                </ul>
                <button class="cta-button">Seleccionar Plan</button>
            </div>
        </section>
    </main>
</section>